=== BenRutlandWeb/recipeasy/src/schemas/recipe.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Recipe",
    "type": "object",
    "required": [
        "title",
        "description",
        "serves",
        "prepTime",
        "cookTime",
        "image",
        "keywords",
        "ingredients",
        "methods"
    ],
    "properties": {
        "$schema": {
            "type": "string"
        },
        "title": {
            "type": "string",
            "description": "The title of the recipe"
        },
        "description": {
            "type": "string",
            "description": "A short description of the recipe"
        },
        "image": {
            "type": "string",
            "description": "An image path"
        },
        "serves": {
            "type": "integer",
            "description": "The number of servings"
        },
        "prepTime": {
            "type": "integer",
            "description": "Preparation time in minutes"
        },
        "cookTime": {
            "type": "integer",
            "description": "Cooking time in minutes"
        },
        "keywords": {
            "type": "array",
            "description": "List of keywords for categorizing the recipe. E.g. Dinner, Breakfast, Meat, Vegan. Avoid ingredients.",
            "items": {
                "type": "string"
            }
        },
        "ingredients": {
            "type": "array",
            "description": "A list of ingredients",
            "items": {
                "$ref": "ingredient.json"
            }
        },
        "methods": {
            "type": "array",
            "description": "Step-by-step instructions",
            "items": {
                "type": "string"
            }
        },
        "diet": {
            "$ref": "diet.json"
        },
        "spiceLevel": {
            "type": "integer",
            "minimum": 0,
            "maximum": 3,
            "default": 0
        }
    },
    "additionalProperties": false
}

=== BenRutlandWeb/recipeasy/src/data/recipes/pork-with-tomatoes-and-red-wine.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Pork with tomatoes and red wine",
  "ingredients": [
    {
      "name": "pork fillet",
      "quantity": 350,
      "unit": "g",
      "description": "Cut into strips"
    },
    { "name": "onion", "quantity": 1, "description": "Chopped" },
    { "name": "chopped tomatoes", "quantity": 400, "unit": "g" },
    { "name": "red wine", "quantity": 150, "unit": "ml" },
    { "name": "tomato puree", "quantity": 1, "unit": "tbsp" },
    { "name": "vegetable stock", "quantity": 150, "unit": "ml" },
    { "name": "Italian mixed herbs", "quantity": 1, "unit": "tsp" },
    {
      "name": "chestnut mushrooms",
      "quantity": 225,
      "unit": "g",
      "description": "Halved"
    },
    { "name": "courgettes", "quantity": 2, "description": "Sliced thickly" },
    { "name": "cornflour", "quantity": 2, "unit": "tsp" }
  ],
  "methods": [
    "Dry-fry the pork and onion for 5 minutes, then stir in the canned tomatoes, red wine, tomato pur√©e, stock, herbs, mushrooms, courgettes and sage.",
    "Bring to the boil, then cover and simmer for 15 minutes.",
    "Blend the cornflour to a paste with just enough water and stir in to the pork mixture.",
    "Simmer uncovered, for 1-2 minutes to thicken the sauce. Season to taste. Serve."
  ],
  "keywords": ["Dinner", "Meat", "Italian"],
  "image": "/recipeasy/pork-with-tomatoes-and-red-wine.jpg",
  "description": "Serve with rice and fresh vegetables.",
  "serves": 4,
  "prepTime": 10,
  "cookTime": 20
}

=== BenRutlandWeb/recipeasy/src/data/recipes/creamy-salmon-pasta.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Creamy salmon pasta",
  "ingredients": [
    { "name": "salmon fillets", "quantity": 2 },
    { "name": "olive oil", "quantity": 1, "unit": "tbsp" },
    { "name": "penne pasta", "quantity": 175, "unit": "g" },
    { "name": "garlic clove", "quantity": 1, "description": "Crushed" },
    {
      "name": "shallots",
      "quantity": 2,
      "description": "Or 1 small onion, finely chopped"
    },
    { "name": "white wine", "quantity": 100, "unit": "ml" },
    {
      "name": "double cream",
      "quantity": 200,
      "unit": "ml",
      "description": "Or crème fraîche"
    },
    { "name": "lemon", "quantity": 0.25, "description": "Zested and juiced" },
    {
      "name": "dill",
      "quantity": 10,
      "unit": "g",
      "description": "Finely chopped"
    }
  ],
  "methods": [
    "Heat the oven to 180C, place the salmon on a baking tray, drizzle with oil and roast for 12 mins.",
    "While the salmon is cooking, boil the pasta for 10 mins until al dente, then drain, reserving 100ml of the pasta water.",
    "Heat the oil on a medium heat in a wide frying pan and fry the shallots for 6 mins until softened. Add the garlic and fry for a minute more until fragrant.",
    "Add the wine, bubble for a few minutes until reduced by half, then add the cream and season well. Bring to a very gentle simmer.",
    "Flake the cooked salmon into big chunky pieces, leaving the skin behind. Add to the sauce with the cooked pasta.",
    "Add the lemon zest, a squeeze of the juice and most of the dill. Toss gently to keep the salmon in big pieces. Serve with a green salad."
  ],
  "keywords": ["Dinner", "Fish", "Italian"],
  "image": "creamy-salmon-pasta.webp",
  "description": "Indulge in this creamy salmon dish for two. It's comforting and filling, and ready in just 30 minutes. Serve with a green salad.",
  "serves": 2,
  "prepTime": 15,
  "cookTime": 15
}

=== BenRutlandWeb/recipeasy/src/data/recipes/chicken-with-sage-and-prosciutto.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Chicken with sage and prosciutto",
  "ingredients": [
    { "name": "parma ham", "quantity": 6, "description": "Slices" },
    { "name": "sage leaves", "quantity": 6 },
    { "name": "chicken breasts", "quantity": 6 },
    { "name": "butter", "quantity": 15, "unit": "g" },
    { "name": "olive oil", "quantity": 2, "unit": "tbsp" },
    { "name": "white wine", "quantity": 100, "unit": "ml" }
  ],
  "methods": [
    "Place Parma ham and a sage leaf on each breast and secure with a wooden cocktail stick.",
    "Heat butter and oil in a large frying pan, then cook breasts on both sides for 5 mins.",
    "Pour half the wine over the chicken, then leave to cook for a further 5 mins.",
    "Add rest of wine to pan and leave to sizzle for a few seconds."
  ],
  "keywords": ["Dinner", "Meat", "Italian"],
  "image": "/recipeasy/thyme-roasted-chicken.webp",
  "description": "A simple, rustic chicken dish, which is pan fried and finished with a splash of Italian wine.",
  "serves": 6,
  "prepTime": 10,
  "cookTime": 20
}

=== BenRutlandWeb/recipeasy/src/data/recipes/chilli-con-carne.json
{
    "$schema": "../../schemas/recipe.json",
    "title": "Chilli Con Carne",
    "ingredients": [
        {
            "name": "onions, finely chopped",
            "quantity": 2
        },
        {
            "name": "red pepper, chopped",
            "quantity": 1
        },
        {
            "name": "minced beef",
            "quantity": 500,
            "unit": "g"
        },
        {
            "name": "kidney beans, drained",
            "quantity": 400,
            "unit": "g"
        },
        {
            "name": "can chopped tomatoes",
            "quantity": 400,
            "unit": "g"
        },
        {
            "name": "Tomato puree",
            "quantity": 3,
            "unit": "tbsp"
        },
        {
            "name": "chili peppers, finely sliced",
            "quantity": 2
        },
        {
            "name": "chili powder",
            "quantity": 3,
            "unit": "tsp"
        },
        {
            "name": "long grain rice",
            "quantity": 300,
            "unit": "g"
        }
    ],
    "methods": [
        "On a medium heat, fry the onions and red pepper in a tbsp of olive oil for 5 minutes or until soft. Add the mince and fry until browned.",
        "Stir in the kidney beans, chopped tomatoes, chilli powder, chilli peppers and tomato puree. Leave to simmer for 30 minutes, stirring occasionally.",
        "Turn the heat down to medium-low. Meanwhile, cook the rice according to the packet instructions.",
        "Serve the chilli on a bed of rice, or alternatively, you can serve over a baked potato or nachos."
    ],
    "keywords": ["dinner", "tex-mex", "meat"],
    "image": "/recipeasy/chilli-con-carne.jpg",
    "description": "",
    "serves": 4,
    "prepTime": 5,
    "cookTime": 60,
    "spiceLevel": 2
}

=== BenRutlandWeb/recipeasy/src/data/recipes/bacon-and-pea-risotto.json
{
    "$schema": "../../schemas/recipe.json",
    "title": "Bacon and Pea Risotto",
    "ingredients": [
        {
            "name": "onion",
            "quantity": 1
        },
        {
            "name": "olive oil",
            "quantity": 2,
            "unit": "tbsp"
        },
        {
            "name": "knob of butter",
            "quantity": 1
        },
        {
            "name": "streaky bacon rashers",
            "quantity": 6,
            "description": "chopped into small chunks"
        },
        {
            "name": "risotto rice",
            "quantity": 300,
            "unit": "g"
        },
        {
            "name": "vegetable stock",
            "quantity": 1,
            "unit": "L"
        },
        {
            "name": "peas",
            "quantity": 100,
            "unit": "g"
        },
        {
            "name": "parmesan cheese",
            "description": "finely grated to serve"
        }
    ],
    "methods": [
        "Finely chop the onion. Heat the olive oil and butter in a pan, add the onions and fry until lightly browned (about 7 minutes).",
        "Add streaky bacon and fry for a further 5 minutes, until it starts to crisp.",
        "Add the risotto rice and hot vegetable stock, and bring to the boil. Stir well, then reduce the heat and cook, covered, for 15-20 minutes until the rice is almost tender.",
        "Stir in the frozen peas, add a little salt and pepper and cook for a further 3 minutes, until the peas are cooked.",
        "Serve sprinkled with freshly grated parmesan and freshly ground black pepper."
    ],
    "keywords": ["dinner", "meat"],
    "image": "/recipeasy/bacon-and-pea-risotto.jpg",
    "description": "Not one for risotto purists - this simple recipe has just a few ingredients and the stock is added all in one go. The result is creamy, comforting yet healthy",
    "serves": 4,
    "prepTime": 5,
    "cookTime": 40
}

=== BenRutlandWeb/recipeasy/src/data/recipes/tarragon-chicken.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Tarragon chicken",
  "ingredients": [
    { "name": "garlic butter", "quantity": 75, "unit": "g" },
    { "name": "olive oil", "quantity": 1, "unit": "tbsp" },
    { "name": "chicken breasts", "quantity": 4, "description": "Cut in half" },
    { "name": "white wine", "quantity": 150, "unit": "ml" },
    { "name": "tarragon", "quantity": 15, "unit": "g" },
    { "name": "green grapes", "quantity": 125, "unit": "g" },
    { "name": "double cream", "quantity": 150, "unit": "ml" },
    { "name": "parsley", "quantity": 10, "unit": "g", "description": "Chopped" }
  ],
  "methods": [
    "Melt the butter and the olive oil in a frying pan over a medium heat, then season the chicken with plenty of salt and freshly ground black pepper. Fry the chicken steaks for approximately 4 mins on each side until golden.",
    "Add white wine, tarragon and grapes to the pan, then bring mixture to the boil and lower the heat. Stir in the cream and parsley and serve immediately with a selection of steamed vegetables and boiled new potatoes."
  ],
  "keywords": ["Dinner", "Meat", "French"],
  "image": "tarragon-chicken.webp",
  "description": "The French love rich sauces made with a hint of wine and a handful of fresh herbs and this mouthwatering dish is based on one of their classic cordon bleu recipes. The combined flavours are so delicious, you won't believe how easy and quick it is to make this lovely dish.",
  "serves": 4,
  "prepTime": 5,
  "cookTime": 15
}

=== BenRutlandWeb/recipeasy/src/data/recipes/chicken-curry.json
{
    "$schema": "../../schemas/recipe.json",
    "title": "Chicken curry",
    "ingredients": [
        { "name": "sunflower oil", "quantity": 2, "unit": "tbsp" },
        { "name": "onion", "quantity": 1, "description": "Thinly sliced" },
        { "name": "garlic cloves", "quantity": 2, "description": "Crushed" },
        { "name": "ginger", "description": "Thumb-sized piece, grated" },
        { "name": "chicken thighs", "quantity": 6, "description": "Boneless and skinless" },
        { "name": "tikka spice paste", "quantity": 3, "unit": "tbsp" },
        { "name": "can chopped tomatoes", "quantity": 400, "unit": "g" },
        { "name": "Greek yoghurt", "quantity": 100, "unit": "g" },
        { "name": "coriander", "quantity": 15, "unit": "g" },
        { "name": "ground almonds", "quantity": 50, "unit": "g" },
        { "name": "basmati rice", "quantity": 300, "unit": "g" }
    ],
    "methods": [
        "Heat the oil in a flameproof casserole dish or large frying pan over a medium heat. Add the onion and a generous pinch of salt and fry for 8-10 mins, or until the onion has turned golden brown and sticky.",
        "Add the garlic and ginger, cooking for a further minute.",
        "Chop the chicken into chunky 3cm pieces, add to the pan and fry for 5 mins.",
        "Stir through the spice paste and chopped tomatoes, along with 250ml water. Bring to the boil, lower to a simmer and cook on a gentle heat uncovered for 25-30 mins or until rich and slightly reduced.",
        "Stir though the yogurt, coriander and ground almonds, season and serve with warm naan or fluffy basmati rice."
    ],
    "keywords": ["Dinner", "Meat", "Indian"],
    "image": "/recipeasy/chicken-curry.jpg",
    "description": "This easy staple chicken curry is a fantastic recipe for family dinners. It's made with just a handful of ingredients and is enriched with creamy yogurt.",
    "serves": 4,
    "prepTime": 5,
    "cookTime": 45
}

=== BenRutlandWeb/recipeasy/src/data/recipes/roast-chorizo-chicken.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Roast chorizo chicken",
  "ingredients": [
    { "name": "new potatoes", "quantity": 500, "unit": "g" },
    { "name": "olive oil", "quantity": 2, "unit": "tbsp" },
    {
      "name": "chicken thighs",
      "quantity": 8,
      "description": "Skinless and boneless"
    },
    { "name": "soked paprika", "quantity": 1, "unit": "tsp" },
    { "name": "thyme", "quantity": 1, "unit": "tsp" },
    { "name": "chorizo", "quantity": 115, "unit": "g" },
    { "name": "cherry tomatoes", "quantity": 150 },
    { "name": "garlic cloves", "quantity": 4 },
    { "name": "parsley", "quantity": 10, "unit": "g" }
  ],
  "methods": [
    "Preheat the oven to 220C/200C Fan/Gas 7. Halve or quarter the potatoes, depending on their size (to produce evenly sized chunks). Place in a large non-stick roasting tin. Toss with two tbsp of the oil and season to taste with salt and pepper, then put into the oven for 15 minutes.",
    "Cut the chicken thighs in half, add the smoked paprika and cinnamon, if using. Scatter with half the thyme leaves, season with salt and pepper, stir through and set aside.",
    "Make a nick in the skin of the chorizo then, peel away the papery skin. Cut the sausage into chunks or rounds.",
    "When the potatoes have had 15 minutes roasting, give them a stir, then nestle the chicken and tomatoes into the pan. Scatter with the chorizo, garlic and the remaining thyme leaves, then season with salt and pepper.",
    "Drizzle the remaining oil all over, and return to the oven to roast for 20 minutes more, stirring half-way, until the chicken is cooked through and the potatoes and tomatoes are turning golden brown and crisp at the edges.",
    "Scatter the dish with a handful roughly chopped parsley, and serve."
  ],
  "keywords": ["Dinner", "Meat"],
  "image": "roast-chorizo-chicken.webp",
  "description": "Tasty chicken and chorizo roasted in the same tin, infusing great paprika and herb flavours, and saving on washing up.",
  "serves": 4,
  "prepTime": 15,
  "cookTime": 45
}
