=== BenRutlandWeb/recipeasy/src/schemas/recipe.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Recipe",
    "type": "object",
    "required": [
        "title",
        "description",
        "serves",
        "prepTime",
        "cookTime",
        "image",
        "keywords",
        "ingredients",
        "methods"
    ],
    "properties": {
        "$schema": {
            "type": "string"
        },
        "title": {
            "type": "string",
            "description": "The title of the recipe"
        },
        "description": {
            "type": "string",
            "description": "A short description of the recipe"
        },
        "image": {
            "type": "string",
            "description": "An image path"
        },
        "serves": {
            "type": "integer",
            "description": "The number of servings"
        },
        "prepTime": {
            "type": "integer",
            "description": "Preparation time in minutes"
        },
        "cookTime": {
            "type": "integer",
            "description": "Cooking time in minutes"
        },
        "keywords": {
            "type": "array",
            "description": "List of keywords for categorizing the recipe. E.g. Dinner, Breakfast, Meat, Vegan. Avoid ingredients.",
            "items": {
                "type": "string"
            }
        },
        "ingredients": {
            "type": "array",
            "description": "A list of ingredients",
            "items": {
                "$ref": "ingredient.json"
            }
        },
        "methods": {
            "type": "array",
            "description": "Step-by-step instructions",
            "items": {
                "type": "string"
            }
        },
        "diet": {
            "$ref": "diet.json"
        },
        "spiceLevel": {
            "type": "integer",
            "minimum": 0,
            "maximum": 3,
            "default": 0
        }
    },
    "additionalProperties": false
}

=== BenRutlandWeb/recipeasy/src/data/recipes/orange-and-apricot-loaf.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Orange and apricot loaf",
  "ingredients": [
    { "name": "butter", "quantity": 175, "unit": "g" },
    { "name": "caster sugar", "quantity": 175, "unit": "g" },
    { "name": "self-raising flour", "quantity": 175, "unit": "g" },
    { "name": "eggs", "quantity": 3 },
    { "name": "orange", "quantity": 1, "description": "Zest and juice" },
    { "name": "ground almonds", "quantity": 35, "unit": "g" },
    { "name": "dessicated coconut", "quantity": 35, "unit": "g" },
    {
      "name": "dried apricots",
      "quantity": 125,
      "unit": "g",
      "description": "Chopped"
    },
    { "name": "Icing sugar", "description": "To dust" }
  ],
  "methods": [
    "Preheat the oven to 170C/fan 150C/gas mark 3. Grease a 900g (2lb) loaf tin and line the base and two long sides with baking paper.",
    "Place the butter, sugar, flour, eggs and the orange rind and juice in a bowl. Beat with an electric whisk until thoroughly combined.",
    "Toss together the ground almonds and apricots and fold into the mixture.",
    "Spoon the mixture into the prepared tin and bake for 50 minutes - 1 hour 10 minutes until risen and golden and a skewer inserted into the centre comes out clean.",
    "Cool for 10 minutes then turn out onto a wire rack and leave to cool completely. Serve dusted with icing sugar and decorated with the extra orange zest."
  ],
  "keywords": ["Dessert", "Baking", "Vegetarian"],
  "image": "orange-and-apricot-loaf.jpg",
  "description": "",
  "serves": 12,
  "prepTime": 20,
  "cookTime": 60,
  "diet": ["vegetarian"]
}

=== BenRutlandWeb/recipeasy/src/data/recipes/mascarpone-and-lime-torte.json
{
    "$schema": "../../schemas/recipe.json",
    "title": "Mascarpone and lime torte",
    "ingredients": [
        { "name": "ginger snap biscuits", "quantity": 200, "unit": "g", "description": "Crushed" },
        { "name": "butter", "quantity": 50, "unit": "g", "description": "Melted" },
        { "name": "mascarpone cheese", "quantity": 500, "unit": "g" },
        { "name": "icing sugar", "quantity": 40, "unit": "g" },
        { "name": "limes", "quantity": 2, "description": "Zest and juice" },
        { "name": "dark chocolate", "quantity": 50, "unit": "g" },
        { "name": "caster sugar", "quantity": 50, "unit": "g" },
        { "name": "Strawberries", "description": "A handful for decoration" }
    ],
    "methods": [
        "Mix together the crushed biscuits and melted butter and press into the base of a 18cm (7 inch) spring sided, or loose bottomed cake tin.",
        "Place the mascarpone, icing sugar, lime zest and juice in a bowl and beat together. Spread over the biscuit base. Chill for 30 minutes.",
        "To decorate, melt the chocolate as per pack instructions. Wash and pat dry some fresh rose leaves. Pull the underside of the leaves along the melted chocolate until coated. Allow leaves to dry coated side up.",
        "Meanwhile to frost the grapes, dip in water, shake off excess and coat with caster sugar.",
        "Then carefully peel away each rose leaf starting at the stem and arrange with the grapes on top of the torte."
    ],
    "keywords": ["Dessert", "Vegetarian"],
    "image": "/recipeasy/mascarpone-and-lime-torte.jpg",
    "description": "Here's a wonderful summer cheesecake dessert that's not only incredibly easy and quick to make but looks and tastes fantastic too.",
    "serves": 1,
    "prepTime": 45,
    "cookTime": 0,
    "diet": ["vegetarian"]
}

=== BenRutlandWeb/recipeasy/src/data/recipes/plum-crumble.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Plum crumble",
  "description": "Use two types of sugar and ground almonds for the perfect crunchy crumble topping, layered on top of cinnamon-spiced plums.",
  "serves": 6,
  "prepTime": 15,
  "cookTime": 40,
  "image": "/recipeasy/plum-crumble.webp",
  "keywords": ["Dessert", "Vegetarian"],
  "ingredients": [
    {
      "name": "plums",
      "quantity": 800,
      "unit": "g",
      "description": "Halved and stoned"
    },
    { "name": "light brown sugar", "quantity": 50, "unit": "g" },
    { "name": "orange", "quantity": 1, "description": "Zested" },
    { "name": "ground cinnamon", "quantity": 1, "unit": "tsp" },
    { "name": "plain flour", "quantity": 250, "unit": "g" },
    { "name": "butter", "quantity": 150, "unit": "g" },
    { "name": "caster sugar", "quantity": 80, "unit": "g" },
    { "name": "demerara sugar", "quantity": 80, "unit": "g" },
    { "name": "ground almonds", "quantity": 50, "unit": "g" }
  ],
  "methods": [
    "Heat the oven to 200C/180C fan/gas 6. Put the plums into the base of a shallow gratin dish about 28cm long.",
    "Mix together the sugar, orange zest, cinnamon and 1tsp flour and sprinkle over the plums. Trickle over 2 tbsp water.",
    "Rub the butter into the flour using your hands and then stir in the other ingredients.",
    "Scatter the crumble over the plums and bake in the oven for 30-40 mins until golden brown.",
    "Leave for about 15 mins before serving with custard or cream."
  ],
  "diet": ["vegetarian"]
}

=== BenRutlandWeb/recipeasy/src/data/recipes/pasta-alla-vodka.json
{
    "$schema": "../../schemas/recipe.json",
    "title": "Pasta alla vodka",
    "ingredients": [
        { "name": "olive oil", "quantity": 2, "unit": "tbsp" },
        { "name": "onion", "quantity": 0.5, "description": "Finely chopped" },
        { "name": "garlic cloves", "quantity": 3, "description": "Crushed" },
        { "name": "chilli flakes", "quantity": 0.25, "unit": "tsp" },
        { "name": "tomato puree", "quantity": 100, "unit": "g" },
        { "name": "vodka", "quantity": 5, "unit": "tbsp" },
        { "name": "double cream", "quantity": 100, "unit": "ml" },
        { "name": "penne pasta", "quantity": 150, "unit": "g" },
        { "name": "parmesan cheese", "quantity": 30, "unit": "g", "description": "Finely grated to serve" },
        { "name": "Basil", "description": "A few sprigs to serve" }
    ],
    "methods": [
        "Heat the oil in a large frying pan or casserole dish. Add the onion and a large pinch of salt and gently fry over a low heat for 10 mins or until softened and translucent.",
        "Add the garlic and chilli flakes and cook for 30 seconds. Stir through the tomato puree, cook for 2 mins, then stir through the vodka and cook for 3 mins.",
        "Quickly stir through the cream to combine, then remove from the heat.",
        "Cook the pasta in salted water following pack instructions. Drain and reserve 150ml cooking water.",
        "Add roughly 50ml of the water to the tomato sauce, then tip in the pasta and cheese, tossing everything together over a low heat until well coated and glossy.",
        "Season to taste, then serve with a sprinkling of the extra parmesan, a good grinding of black pepper and the basil leaves scattered over the top."
    ],
    "keywords": ["Dinner", "Italian", "Vegetarian"],
    "image": "/recipeasy/pasta-alla-vodka.jpg",
    "description": "Sit back and tuck into a big bowl of pasta alla vodka, a creamy tomato pasta with - as you can guess - vodka, which balances out the intense flavours.",
    "serves": 2,
    "prepTime": 5,
    "cookTime": 25,
    "diet": ["vegetarian"]
}

=== BenRutlandWeb/recipeasy/src/data/recipes/garlic-butter-mussels-with-spaghetti.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Garlic butter mussels with spaghetti",
  "ingredients": [
    { "name": "spaghetti pasta", "quantity": 150, "unit": "g" },
    {
      "name": "mussels",
      "quantity": 200,
      "unit": "g",
      "description": "Cooked and prepared, de-shelled"
    },
    { "name": "garlic cloves", "quantity": 4, "description": "Finely sliced" },
    { "name": "butter", "quantity": 20, "unit": "g" },
    { "name": "chilli flakes", "quantity": 0.5, "unit": "tsp" },
    { "name": "parsley", "quantity": 2, "unit": "tsp" }
  ],
  "methods": [
    "Bring a pan of salted water to a boil for cooking the spaghetti. Once boiling add the pasta and begin to cook. Meanwhile in a large frying pan over a medium heat add the butter and allow to melt.",
    "Add the finely chopped garlic to the melted butter and a good pinch of chilli flakes. Gently fry until fragrant.",
    "Add the cooked mussels and simmer them gently in the butter to heat through. Add a grind of black pepper and a tiny bit of salt (the mussels are already salty so don't add a lot). Check on the pasta.",
    "Stir the mussels so that they are coated in the butter garlic and chilli sauce evenly. Turn down the heat to low.",
    "Drain off the spaghetti once el dente and add into the frying pan with the mussels using tongs gently toss everything together. Add the parsley and a touch more pepper. Toss until every strand is coated in the butter sauce. Serve up immediately and enjoy!"
  ],
  "keywords": ["Dinner", "Seafood", "Italian"],
  "image": "garlic-butter-mussels-with-spaghetti.webp",
  "description": "This recipe is pure simplicity but packs some big flavour. This dish also works beautifully with tender and succulent prawns if you prefer them to mussels.",
  "serves": 2,
  "prepTime": 5,
  "cookTime": 10
}

=== BenRutlandWeb/recipeasy/src/data/recipes/pork-with-lemon-and-pine-nuts.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Pork with lemon and pine nuts",
  "ingredients": [
    { "name": "pork fillet", "quantity": 500, "unit": "g" },
    {
      "name": "parsley",
      "quantity": 15,
      "unit": "g",
      "description": "Coarsly chopped"
    },
    {
      "name": "plain flour",
      "quantity": 15,
      "unit": "g",
      "description": "Seasoned with salt and pepper"
    },
    { "name": "pine nuts", "quantity": 25, "unit": "g" },
    { "name": "lemon", "quantity": 1, "description": "Zest and juice" },
    { "name": "honey", "quantity": 1, "unit": "tbsp" },
    { "name": "tagliatelle pasta", "quantity": 300, "unit": "g" }
  ],
  "methods": [
    "Cut the pork into 2cm thick slices. Toss in seasoned flour to coat very lightly and shake of the excess.",
    "Heat 1 tbsp of olive oil in a large frying pan and fry the pork in a single layer for a few minutes on each side or until browned. Remove from the pan and keep warm.",
    "Add another tbsp of oil to the pan and fry the pine nuts until lightly browned.",
    "Stir in the lemon zest, juice and honey. Bubble and stir briefly to make a sauce.",
    "Return the pork to the pan and add the parsley. Continue to cook for another few minutes to heat through.",
    "Serve with buttered papperdelle or tagliatelle."
  ],
  "keywords": ["Dinner", "Meat", "Italian"],
  "image": "pork-with-lemon-and-pine-nuts.jpg",
  "description": "",
  "serves": 4,
  "prepTime": 5,
  "cookTime": 15
}

=== BenRutlandWeb/recipeasy/src/data/recipes/pad-kra-pao.json
{
    "$schema": "../../schemas/recipe.json",
    "title": "Pad Kra Pao",
    "ingredients": [
        {
            "name": "minced pork",
            "quantity": 250,
            "unit": "g"
        },
        {
            "name": "cloves garlic, crushed",
            "quantity": 2
        },
        {
            "name": "birds eye chillis, finely chopped",
            "quantity": 3
        },
        {
            "name": "long beans, chopped",
            "quantity": 2
        },
        {
            "name": "Thai basil",
            "quantity": 15,
            "unit": "g"
        },
        {
            "name": "vegetable oil",
            "quantity": 4,
            "unit": "tbsp"
        },
        {
            "name": "oyster sauce",
            "quantity": 1,
            "unit": "tbsp"
        },
        {
            "name": "fish sauce",
            "quantity": 1,
            "unit": "tbsp"
        },
        {
            "name": "soy sauce",
            "quantity": 1,
            "unit": "tbsp"
        },
        {
            "name": "dark soy sauce",
            "quantity": 1,
            "unit": "tbsp"
        },
        {
            "name": "brown sugar",
            "quantity": 1,
            "unit": "tbsp"
        },
        {
            "name": "jasmine rice",
            "quantity": 150,
            "unit": "g"
        }
    ],
    "methods": [
        "Heat the oil in a wok. Add the crushed garlic and finely chopped chilli peppers and fry until fragrant.",
        "Add the minced pork and stir-fry until cooked.",
        "Meanwhile, combine the oyster sauce, fish sauce, soy sauce, dark soy sauce and brown sugar. Add a little water if needed to get a thick sauce consistency.",
        "Add the sauce to the wok and stir-fry for about 10 minutes.",
        "Turn off the heat and add the Thai basil, mix well and serve with jasmine or sticky rice."
    ],
    "keywords": ["dinner", "thai", "meat"],
    "image": "/recipeasy/pad-kra-pao.jpg",
    "description": "",
    "serves": 2,
    "prepTime": 10,
    "cookTime": 25,
    "spiceLevel": 3
}

=== BenRutlandWeb/recipeasy/src/data/recipes/chicken-souvlaki.json
{
  "$schema": "../../schemas/recipe.json",
  "title": "Chicken souvlaki",
  "ingredients": [
    {
      "name": "chicken thighs",
      "quantity": 12,
      "description": "Boneless, skinless"
    },
    { "name": "olive oil", "quantity": 4, "unit": "tbsp" },
    { "name": "dried oregano", "quantity": 2, "unit": "tsp" },
    { "name": "dried mint", "quantity": 1, "unit": "tsp" },
    { "name": "ground cumin", "quantity": 1, "unit": "tsp" },
    { "name": "coriander", "quantity": 1, "unit": "tsp" },
    { "name": "sweet paprika", "quantity": 1, "unit": "tsp" },
    {
      "name": "lemon",
      "quantity": 1,
      "description": "Juice and zest, plus 1 lemon cut into wedges to serve"
    },
    { "name": "garlic cloves", "quantity": 4, "description": "Crushed" },
    { "name": "pitta wraps", "quantity": 4 },
    { "name": "Tzatziki" }
  ],
  "methods": [
    "Tip the chicken into a large bowl and add the marinade ingredients, along with 1 tsp salt and plenty of black pepper. Mix well, ensuring each thigh is well coated. Cover and chill for at least 3 hrs, or up to 48 hrs if you have time.",
    "Heat the grill to its highest setting. Line a roasting tin with foil and find metal skewers long enough to sit across the top with a little space underneath. Take one thigh and thread it over 2 skewers, so it has a skewer through either side. Thread another piece of chicken on top, leaving a slight gap between each piece; you should fit 6 thighs on each pair of skewers. Position the skewers on top of the roasting tin and set aside while you finish the pittas.",
    "Heat the pitta wraps as per the packet instructions and keep warm in the bottom of the oven while you cook the chicken.",
    "Put the chicken under the hot grill and cook for 15-20 mins, brushing with oil and any juices from the bottom of the tin regularly, and turning halfway through cooking. Once cooked, remove from the oven and rest for 5 mins. Alternatively you can cook the chicken skewers on the barbecue.",
    "Cut through each pair of skewers to make seperate kebabs and serve in the warm bread, with lettuce, tomato, red onion, lemon wedges and tzatziki."
  ],
  "keywords": ["Dinner", "Meat", "Greek"],
  "image": "/recipeasy/chicken-souvlaki.webp",
  "description": "Marinate the chicken for as long as possible to soak up all the flavour and make it really tender. Serve with warm bread, salad and tzatziki.",
  "serves": 4,
  "prepTime": 45,
  "cookTime": 40
}
